pipeline {
    agent any

    environment {
        DJANGO_SETTINGS_MODULE = "mac.settings"
        DATABASE_URL = "sqlite://db.sqlite3"
        DOCKER_IMAGE = "ziasaeeditgeek/django-application"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: "main", url: "https://github.com/Zia-Saeed/Django-CICD-PROJECT"
            }
        }

        stage('Install Dependencies') {
            agent {
                docker {
                    image "python:3.12-slim"
                    args "--user root -v /var/run/docker.sock:/var/run/docker.sock"
                }
            }
            steps {
                dir('mac') {
                    sh 'pip install --upgrade pip'
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('Build and Push Docker Image') {
            environment {
                REGISTRY_CREDENTIALS = credentials('docker-cred')
            }
            steps {
                script {
                    // Build Docker image
                    sh "docker build -t ${env.DOCKER_IMAGE}:${env.BUILD_NUMBER} ./mac"

                    // Push Docker image
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
                        docker.image("${env.DOCKER_IMAGE}:${env.BUILD_NUMBER}").push()
                    }
                }
            }
        }

        stage('Update Kubernetes Manifest') {
            steps {
                withCredentials([string(credentialsId: "github-token", variable: "GITHUB_TOKEN")]) {
                    script {
                        // Checkout the main branch explicitly
                        sh 'git checkout main'

                        // Update the image tag in the Kubernetes manifest
                        sh """
                        sed -i 's|image: ${env.DOCKER_IMAGE}:.*|image: ${env.DOCKER_IMAGE}:${env.BUILD_NUMBER}|g' kubernetes/deployment.yml
                        """

                        // Commit and push changes
                        sh """
                        git config --global user.name "Jenkins"
                        git config --global user.email "jenkins@example.com"
                        git add kubernetes/deployment.yml
                        git commit -m "Update image tag to ${env.BUILD_NUMBER}"
                        git push https://${GITHUB_TOKEN}@github.com/Zia-Saeed/Django-CICD-PROJECT HEAD:main
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline Succeeded!"
        }
        failure {
            echo "Pipeline Failed"
        }
    }
}
